steps: 

- name: 'gcr.io/cloud-builders/docker'
  args: ['build' , '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique-repo/frontend:latest', './src/frontend']

# Step 2: Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/online-boutique-repo/frontend:latest']


options:
  logging: CLOUD_LOGGING_ONLY
